export enum MutationTypes {
  SET_NUMBER = "SET_NUMBER",
  SET_SCORE = "SET_SCORE",
  SET_QUESTIONS = "SET_QUESTIONS",
  SET_USER_ANSWER = "SET_USER_ANSWER",
  SET_GAME_OVER = "SET_GAME_OVER",
  SET_LOADING = "SET_LOADING"
}
